FROM python:3.10.13-slim

WORKDIR /app

COPY requirements-frontend.txt .
RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY ./frontend /app/frontend

EXPOSE 8501

CMD ["sh", "-c", "cd frontend && streamlit run frontend-app.py"]
